services:
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"

  web1:
    build: ./web
    image: "${ECR_REGISTRY}/web1:latest"
    container_name: web1
    ports:
      - "5001:5000"
    restart: on-failure
    depends_on:
      - redis

  web2:
    build: ./web
    image: "${ECR_REGISTRY}/web2:latest"
    container_name: web2
    ports:
      - "5002:5000"
    restart: on-failure
    depends_on:
      - redis

  nginx:
    build: ./nginx
    image: "${ECR_REGISTRY}/nginx:latest"
    container_name: nginx
    ports:
      - "80:80"
    depends_on:
      - web1
      - web2
