version: "3.9"

services:

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"

  web1:
    build: ./web
    image: "${ECR_REGISTRY}/web1:latest"
    container_name: web1
    restart: always
    ports:
      - "81:5000"
    depends_on:
      - redis

  web2:
    build: ./web
    image: "${ECR_REGISTRY}/web2:latest"
    container_name: web2
    restart: always
    ports:
      - "82:5000"
    depends_on:
      - redis

  nginx:
    build: ./nginx
    image: "${ECR_REGISTRY}/nginx:latest"
    container_name: ngi_
